language: php
php:
    - 5.3
    - 5.4
before_script:
    - sudo apt-get install -qq memcachedb
    - sudo apt-get install php5-memcached
    - sudo cp /etc/php5/conf.d/memcached.ini /etc/php5/cli/conf.d
    - composer install

